apiVersion: v1
kind: Namespace
metadata:
  name: source
  labels:
    source: "true"
---
kind: Pod
apiVersion: v1
metadata:
  labels:
    app: nginx
  name: nginx-source
  namespace: source
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-source
  namespace: source
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.240.0.35
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-allow-80
  namespace: source
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          source: "true"
      podSelector:
        matchLabels:
          app: nginx
    ports:
    - protocol: TCP
      port: 80
