apiVersion: v1
kind: Namespace
metadata:
  name: destination
  labels:
    destination: "true"
---
kind: Pod
apiVersion: v1
metadata:
  labels:
    app: nginx
  name: nginx-destination
  namespace: destination
spec:
  containers:
  - image: nginx
    imagePullPolicy: Always
    name: nginx
    ports:
    - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-destination
  namespace: destination
  annotations:
    service.beta.kubernetes.io/azure-load-balancer-internal: "true"
    external-dns.alpha.kubernetes.io/hostname: "destination.nginx-test.io"
spec:
  type: LoadBalancer
  loadBalancerIP: 10.240.0.36
  externalTrafficPolicy: Cluster
  ports:
  - port: 80
    targetPort: 80
  selector:
    app: nginx
---
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: api-allow-80
  namespace: destination
spec:
  podSelector:
    matchLabels:
      app: nginx
  policyTypes:
  - Ingress
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          source: "true"
      podSelector:
        matchLabels:
          app: nginx
    ports:
    - protocol: TCP
      port: 80
